# Generated by Django 2.2.6 on 2019-11-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0002_film_filmactor_language'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='Actor',
        ),
        migrations.AlterModelTable(
            name='film',
            table='Film',
        ),
    ]
